# Generated by Django 5.2 on 2025-06-03 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuaHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mach', models.IntegerField()),
                ('ten', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('makh', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=50)),
                ('dchi', models.CharField(blank=True, max_length=50, null=True)),
                ('sodt', models.CharField(blank=True, max_length=15, null=True)),
                ('ngsinh', models.DateTimeField(blank=True, null=True)),
                ('ngdk', models.DateTimeField(blank=True, null=True)),
                ('doanhso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khach_hang', to='qlbh.cuahang')),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('manv', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=50)),
                ('sodt', models.CharField(blank=True, max_length=15, null=True)),
                ('ngvl', models.DateTimeField(blank=True, null=True)),
                ('ch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nhan_vien', to='qlbh.cuahang')),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('sohd', models.IntegerField(primary_key=True, serialize=False)),
                ('nghd', models.DateTimeField(blank=True, null=True)),
                ('trigia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('makh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qlbh.khachhang')),
                ('manv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qlbh.nhanvien')),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('masp', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('tensp', models.CharField(max_length=40)),
                ('dvt', models.CharField(blank=True, max_length=20, null=True)),
                ('nuocsx', models.CharField(blank=True, max_length=40, null=True)),
                ('gia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='san_pham', to='qlbh.cuahang')),
            ],
        ),
        migrations.CreateModel(
            name='CTHD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl', models.IntegerField(blank=True, null=True)),
                ('sohd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlbh.hoadon')),
                ('masp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qlbh.sanpham')),
            ],
            options={
                'unique_together': {('sohd', 'masp')},
            },
        ),
    ]
