# Generated by Django 5.2 on 2025-06-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qlbh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='ch',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='ch',
        ),
        migrations.RemoveField(
            model_name='nhanvien',
            name='ch',
        ),
        migrations.DeleteModel(
            name='CuaHang',
        ),
    ]
